baseURL = "https://LucasCairns.github.io/web-services-in-rust-presentation"
languageCode = "en-us"
title = "Writing web services in Rust"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true